// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._(); // Private constructor to prevent instantiation

  /// Returns appropriate FirebaseOptions for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw _unsupportedPlatformError('windows');
      case TargetPlatform.linux:
        throw _unsupportedPlatformError('linux');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Helper method to throw UnsupportedError
  static UnsupportedError _unsupportedPlatformError(String platform) {
    return UnsupportedError(
      'DefaultFirebaseOptions have not been configured for $platform - '
      'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBSWr0MZg6oM_19JlD0-ymVOXuhX3_Dwm8",
    authDomain: "mtgcompanion-b5d89.firebaseapp.com",
    projectId: "mtgcompanion-b5d89",
    storageBucket: "mtgcompanion-b5d89.appspot.com",
    messagingSenderId: "534334359856",
    appId: "1:534334359856:web:cd8e417df61bbb26fe60f5",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogoEx0H_1klJglqQxtls-7S436awx9iI',
    appId: '1:534334359856:android:9e4430bd836f0cc9fe60f5',
    messagingSenderId: '534334359856',
    projectId: 'mtgcompanion-b5d89',
    storageBucket: 'mtgcompanion-b5d89.appspot.com',
  );
}
